name: Test
on: push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test with Rocky Linux 8
        run: bash bats-RockyLinux8.sh backcheck.bats
      - name: Run test with Rocky Linux 9
        run: bash bats-RockyLinux9.sh backcheck.bats
